language: java
jdk:
  - oraclejdk8
services:
  - docker
before_install:
install: cd jarslink-api && mvn -B -DjacocoReports=/target/site/jacoco-aggregate/jacoco.xml clean test jacoco:report-aggregate coveralls:report
